version: '3.8'

services:
  db:
    image: mysql:8.4.1
    container_name: tarachat_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
