services:
  db:
    image: mysql:8.4.1
    container_name: strangerchat_container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - strangerchat_network

volumes:
  db-data:

networks:
  strangerchat_network: